export const adminIds = ["114347310130195159940", "103712296288785535435"];

export const initialTags = [
    "Software Engineer",
    "Front-end Developer",
    "Back-end Developer",
    "Full Stack Developer",
    "UI/UX Designer",
    "Data Scientist",
    "DevOps Engineer",
    "Machine Learning Engineer",
    "Cybersecurity Specialist",
    "Database Administrator",
    "Systems Analyst",
    "Cloud Engineer",
    "IT Project Manager",
    "Network Engineer",
    "QA Engineer",
    "Embedded Systems Engineer",
    "Site Reliability Engineer",
    "IT Consultant",
    "Technical Support Specialist",
    "Game Developer",
    "Mobile App Developer",
    "Software Architect",
    "IT Auditor",
    "Technical Writer",
    "Web Developer",
    "IT Operations Manager",
];
